- generator/default_values.yaml
- generator/templates/manifests/deploykf-core/deploykf-dashboard/values.yaml
Similar to links in the sidebar, this commit updates the values files to allow configuring the documentation links section on the dashboard home page.
Adds the `deploykf_core.deploykf_dashboard.navigation.documentationItems` value, which is a list of links.
> feat: allow custom documentation links in dashboard

- generator/templates/manifests/deploykf-opt/deploykf-minio/templates/minio/Deployment.yaml
- generator/templates/manifests/deploykf-opt/deploykf-minio/templates/minio/Job-create-buckets.yaml
- generator/templates/manifests/deploykf-opt/deploykf-minio/templates/minio/Job-create-policies.yaml
- generator/templates/manifests/deploykf-opt/deploykf-minio/templates/minio/Job-create-service-accounts.yaml
- generator/templates/manifests/deploykf-opt/deploykf-minio/values.yaml
This PR addresses permission issues that may be encountered for some kinds of PVC StorageClasses used by the MinIO pods by setting PodSecurityContext `fsGroup` to `1000`.
__NOTE:__ this fix was [already applied to MySQL](https://github.com/deployKF/deployKF/blob/v0.1.0/generator/templates/manifests/deploykf-opt/deploykf-mysql/values.yaml#L46-L52), but was missed on the MinIO pods.
> fix: set `securityContext.fsGroup` on minio pods

- generator/default_values.yaml
This PR updates the default minio container image tags. This is mainly to pick up the fix for https://github.com/minio/console/issues/2929, which was preventing users from downloading files that they should have had access to (due to a UI glitch).
The new default image tags are:
- `minio/minio`: `RELEASE.2023-08-04T17-40-21Z`
- `minio/mc`: `RELEASE.2023-08-01T23-30-57Z`
> fix: minio-console user permissions (update minio)

- generator/default_values.yaml
- generator/helpers/check-values--incompatible-configs.tpl
- generator/templates/app-of-apps.yaml
- generator/templates/argocd/deploykf-core/deploykf-auth.yaml
- generator/templates/argocd/deploykf-core/deploykf-dashboard.yaml
- generator/templates/argocd/deploykf-core/deploykf-istio-gateway.yaml
- generator/templates/argocd/deploykf-core/deploykf-profiles-generator.yaml
- generator/templates/argocd/deploykf-dependencies/cert-manager.yaml
- generator/templates/argocd/deploykf-dependencies/istio.yaml
- generator/templates/argocd/deploykf-dependencies/kyverno.yaml
- generator/templates/argocd/deploykf-opt/deploykf-minio.yaml
- generator/templates/argocd/deploykf-opt/deploykf-mysql.yaml
- generator/templates/argocd/kubeflow-dependencies/kubeflow-argo-workflows.yaml
- generator/templates/argocd/kubeflow-tools/katib.yaml
- generator/templates/argocd/kubeflow-tools/notebooks--jupyter-web-app.yaml
- generator/templates/argocd/kubeflow-tools/notebooks--notebook-controller.yaml
- generator/templates/argocd/kubeflow-tools/pipelines.yaml
- generator/templates/argocd/kubeflow-tools/poddefaults-webhook.yaml
- generator/templates/argocd/kubeflow-tools/tensorboards--tensorboard-controller.yaml
- generator/templates/argocd/kubeflow-tools/tensorboards--tensorboards-web-app.yaml
- generator/templates/argocd/kubeflow-tools/training-operator.yaml
- generator/templates/argocd/kubeflow-tools/volumes--volumes-web-app.yaml
- generator/templates/argocd/kustomization.yaml
- generator/templates/manifests/kubeflow-tools/pipelines/resources/generate-profile-resources-clusterpolicy.yaml
- sample-values.yaml
This PR enables a single instance of ArgoCD to manage deployKF across multiple clusters. 
For example, it is common to have an ArgoCD "management cluster" which deploys applications to other Kubernetes clusters, so those clusters don't need to have ArgoCD installed separately.
This is achieved by adding the following values:
- `argocd.appNamePrefix`: 
- Previously you could only apply one instance of the deployKF ArgoCD Applications to a cluster (as the names would overlap), this value lets you prefix the application names.
- `argocd.destination.name`:
- Allows setting the `spec.destination.name` of the Application resources, in addition to our already existing `argocd.destination.server` value for setting `spec.destination.server`.
> feat: allow a single ArgoCD to manage deployKF across multiple clusters

- generator/templates/manifests/deploykf-dependencies/kyverno/values.yaml
related: https://github.com/deployKF/deployKF/issues/24
Currently, [Kyverno `1.10` will not clean up its `ValidatingWebhookConfigurations` and `MutatingWebhookConfigurations`  when uninstalled](https://github.com/kyverno/kyverno/issues/8390), which will always result in the cluster being deadlocked. This is because Kyverno's webhooks intercept most Kubernetes API requests for validation, and if Kyverno no longer exists, it will fail.
This PR tells Kyverno to "fail open" on the resource webook, to prevent this issue.
We can revert this change once https://github.com/kyverno/kyverno/issues/8390 is resolved.
---
Note, that the webhooks will still be left on uninstall with this change, they won't deadlock the cluster.
To remove the webhooks fully, [follow Kyverno's …
> fix: set kyverno webhook failure policy to ignore (fix uninstall deadlock)

- generator/default_values.yaml
- generator/templates/argocd/deploykf-dependencies/cert-manager.yaml
- generator/templates/manifests/deploykf-dependencies/cert-manager/.helmignore
- generator/templates/manifests/deploykf-dependencies/cert-manager/forks/trust-manager/Chart.yaml
- generator/templates/manifests/deploykf-dependencies/cert-manager/forks/trust-manager/FORK.md
- generator/templates/manifests/deploykf-dependencies/cert-manager/forks/trust-manager/templates/NOTES.txt
- generator/templates/manifests/deploykf-dependencies/cert-manager/forks/trust-manager/templates/_helpers.tpl
- generator/templates/manifests/deploykf-dependencies/cert-manager/forks/trust-manager/templates/certificate.yaml
- generator/templates/manifests/deploykf-dependencies/cert-manager/forks/trust-manager/templates/clusterrole.yaml
- generator/templates/manifests/deploykf-dependencies/cert-manager/forks/trust-manager/templates/clusterrolebinding.yaml
- generator/templates/manifests/deploykf-dependencies/cert-manager/forks/trust-manager/templates/deployment.yaml
- generator/templates/manifests/deploykf-dependencies/cert-manager/forks/trust-manager/templates/metrics-service.yaml
- generator/templates/manifests/deploykf-dependencies/cert-manager/forks/trust-manager/templates/metrics-servicemonitor.yaml
- generator/templates/manifests/deploykf-dependencies/cert-manager/forks/trust-manager/templates/role.yaml
- generator/templates/manifests/deploykf-dependencies/cert-manager/forks/trust-manager/templates/rolebinding.yaml
- generator/templates/manifests/deploykf-dependencies/cert-manager/forks/trust-manager/templates/serviceaccount.yaml
- generator/templates/manifests/deploykf-dependencies/cert-manager/forks/trust-manager/templates/trust.cert-manager.io_bundles.yaml
- generator/templates/manifests/deploykf-dependencies/cert-manager/forks/trust-manager/templates/webhook.yaml
- generator/templates/manifests/deploykf-dependencies/cert-manager/forks/trust-manager/values.yaml
- generator/templates/manifests/deploykf-dependencies/cert-manager/templates/ClusterIssuer-kubeflow-gateway-issuer.yaml
- generator/templates/manifests/deploykf-dependencies/cert-manager/templates/selfsigned-ca-issuer/Bundle.yaml
- generator/templates/manifests/deploykf-dependencies/cert-manager/templates/selfsigned-ca-issuer/Certificate.yaml
- generator/templates/manifests/deploykf-dependencies/cert-manager/templates/selfsigned-ca-issuer/Issuer.yaml
- generator/templates/manifests/deploykf-dependencies/cert-manager/values.yaml
resolves https://github.com/deployKF/deployKF/issues/23
This PR resolves a number of race conditions when installing/upgrading the cert-manager app:
1. Ensures `Certificates` and `Issuers` are sequenced correctly.
2. Ensures that `cert-manager` is up, before `trust-manager` is synced
- __WARNING:__ this required forking the `trust-manager` helm chart, which will require an updated version of the deployKF ArgoCD Plugin (from PR https://github.com/deployKF/deployKF/pull/29)
3. Adds a default ArgoCD sync retry (because even with proper sequencing, stuff can still take time to provision)
> fix: resolve cert-manager race conditions

- argocd-plugin/argocd-install/deploykf-plugin/plugin.yaml
required for https://github.com/deployKF/deployKF/pull/28
This PR fixes the following issues in the deployKF ArgoCD Plugin:
- helm charts with `file://` dependencies should not fail (only add `http(s)://` ones)
- updating the `repository` of a dependency should not fail (adds `--force-update`)
> fix: argocd plugin with "file://" dependencies (needed for helm forks)

- generator/templates/argocd/namespaces/kustomization.yaml
Because users may store other things in the deployKF namespaces (especially the ones for dependencies), we should never automatically delete them.
This PR ensures that ArgoCD will never "prune" (on sync) or "delete" (on app uninstall) a namespace.
__WARNING:__ this does NOT apply to the profile namespaces, which the profile controller will delete as soon as their `Profile` cluster-resource is removed.
> fix: ensure namespaces are never deleted or pruned

- generator/templates/argocd/applications/deploykf-core/deploykf-auth.yaml
- generator/templates/argocd/applications/deploykf-core/deploykf-dashboard.yaml
- generator/templates/argocd/applications/deploykf-core/deploykf-istio-gateway.yaml
- generator/templates/argocd/applications/deploykf-core/deploykf-profiles-generator.yaml
- generator/templates/argocd/applications/deploykf-dependencies/cert-manager.yaml
- generator/templates/argocd/applications/deploykf-dependencies/istio.yaml
- generator/templates/argocd/applications/deploykf-dependencies/kyverno.yaml
- generator/templates/argocd/applications/deploykf-opt/deploykf-minio.yaml
- generator/templates/argocd/applications/deploykf-opt/deploykf-mysql.yaml
- generator/templates/argocd/applications/kubeflow-dependencies/kubeflow-argo-workflows.yaml
- generator/templates/argocd/applications/kubeflow-tools/katib.yaml
- generator/templates/argocd/applications/kubeflow-tools/notebooks--jupyter-web-app.yaml
- generator/templates/argocd/applications/kubeflow-tools/notebooks--notebook-controller.yaml
- generator/templates/argocd/applications/kubeflow-tools/pipelines.yaml
- generator/templates/argocd/applications/kubeflow-tools/poddefaults-webhook.yaml
- generator/templates/argocd/applications/kubeflow-tools/tensorboards--tensorboard-controller.yaml
- generator/templates/argocd/applications/kubeflow-tools/tensorboards--tensorboards-web-app.yaml
- generator/templates/argocd/applications/kubeflow-tools/training-operator.yaml
- generator/templates/argocd/applications/kubeflow-tools/volumes--volumes-web-app.yaml
- generator/templates/argocd/applications/namespaces.yaml
resolves https://github.com/deployKF/deployKF/issues/24
This PR adds ArgoCD sync waves to the Applications. While this only affects the order that the apps are synced to the cluster (not the syncing of the manifests they contain), it does affect the order ArgoCD will delete them in, if the user deletes the `deploykf-app-of-apps`. Upon deletion, ArgoCD will delete resources in reverse sync-wave order.
We have ordered the waves in this PR so that things should be deleted BEFORE the things which they depend on.
The most important one is `dkf-core--deploykf-profiles-generator` must be deleted BEFORE `dkf-core--deploykf-dashboard` (the profiles have a finalizer that the profile controller must remove).
Also, adding these sync waves has allowed the creation of a script to automatically sync (at …
> fix: add sync waves to argocd apps (fix deletion)

- generator/templates/argocd/applications/deploykf-core/deploykf-profiles-generator.yaml
This PR sets a default ArgoCD retry on the `dkf-core--deploykf-profiles-generator` application.
This is needed because the profile generator creates resources in profile namespaces, but the profile controller takes a few seconds to provision the namespaces, causing failure on the first sync of a new profile.
> fix: resolve profile generator race condition

- generator/templates/manifests/kubeflow-dependencies/kubeflow-argo-workflows/templates/ClusterPolicy-clone-bucket-secret.yaml
- generator/templates/manifests/kubeflow-tools/katib/resources/clone-mysql-secret-clusterpolicy.yaml
- generator/templates/manifests/kubeflow-tools/pipelines/resources/clone-bucket-secret-clusterpolicy.yaml
- generator/templates/manifests/kubeflow-tools/pipelines/resources/clone-mysql-secret-clusterpolicy.yaml
This PR addresses race conditions between cloned Secrets and the Pods which mount them.
This is achieved by setting the  `argocd.argoproj.io/sync-wave` to `-1` on the Kyverno `ClusterPolicies` responsible for  cloning these secrets, ensuring they are always synced before the rest of their apps.
> fix: resolve race conditions with cloned secrets

- generator/templates/app-of-apps.yaml
Currently when using "Manifests Repo" Mode, the generated `deploykf-app-of-apps` targets the `argocd.destination`, which is not correct. Even if the internal apps target a remote cluster, the apps themselves should be in the Argo CD cluster.
> fix: app-of-apps should always target argocd cluster

- scripts/README.md
- scripts/sync_argocd_apps.sh
This PR adds a new  `sync_argocd_apps.sh` script under the `scripts/` folder of the repo.
The purpose of this script is to automate the process of syncing all the ArgoCD applications that make up deployKF.
It is designed to follow the correct ordering laid out by the sync waves added in https://github.com/deployKF/deployKF/pull/32.
The script is NOT intended to be used with deployKF versions older than `0.1.2`.
> docs: add reference `sync_argocd_apps.sh` script

- scripts/README.md
- scripts/sync_argocd_apps.sh
This PR adds requirement checks to the `sync_argocd_apps.sh` script so we can prevent confusing errors when using an incompatible bash version, or when other dependencies are missing.
Apparently macOS ships with a version of bash from 2007 by default (version 3.2), which is not new enough to run the `sync_argocd_apps.sh` script.
> docs: add requirement checks to argocd sync script

- generator/default_values.yaml
- generator/templates/manifests/deploykf-core/deploykf-auth/templates/oauth2-proxy/Deployment.yaml
This PR updates the default version of `oauth2-proxy` to `7.5.1`.
__WARNING:__ we make use of the new `/ready` HTTP path that was added in `7.5.0`, so we no longer support `7.4` versions of `oauth2-proxy`.
> feat: update oauth2-proxy to 7.5.1

- generator/default_values.yaml
- generator/templates/manifests/deploykf-core/deploykf-auth/templates/dex/Secret-config.yaml
- generator/templates/manifests/deploykf-core/deploykf-auth/templates/oauth2-proxy/Secret-config.yaml
- generator/templates/manifests/deploykf-core/deploykf-auth/values.yaml
- generator/templates/manifests/deploykf-core/deploykf-istio-gateway/templates/gateway/EnvoyFilter-ext-authz-disable.yaml
- generator/templates/manifests/deploykf-core/deploykf-istio-gateway/templates/gateway/EnvoyFilter-ext-authz.yaml
- generator/templates/manifests/deploykf-core/deploykf-istio-gateway/templates/gateway/EnvoyFilter-kubeflow-pipelines.yaml
- generator/templates/manifests/deploykf-core/deploykf-istio-gateway/templates/gateway/EnvoyFilter-xff-num-trusted-hops.yaml
- generator/templates/manifests/deploykf-core/deploykf-istio-gateway/values.yaml
This PR adds support for browser-based authentication (also known as "out-of-band" OIDC login) with the _Kubeflow Pipelines SDK_.
This is achieved by making the following changes:
- Adding a public OIDC client to Dex named `kubeflow-pipelines-sdk`
- Using the Dex `urn:ietf:wg:oauth:2.0:oob` redirect URI (prompts the user to copy a code)
- Configuring oauth2-proxy to trust requests with a bearer JWT (not only with its own cookie)
We have also added another layer of security where we can restrict HTTP paths depending on the JWT bearer `aud`.
For example, JWT tokens generated under the new `kubeflow-pipelines-sdk` OIDC client, can ONLY access the `/pipelines` API path, but NOT the deployKF dashboard or any other paths.
> feat: browser-based KFP SDK auth

- generator/helpers/deploykf-gateway.tpl
This PR fixes a bug where we followed the self-signed gateway code path when the user brought their own `cert-manager` deployment, unless they explicitly did something like disabling `deploykf_dependencies.cert_manager.clusterIssuer.enabled`.
As there is no reasonable case where someone would want to bring their own `cert-manager` but use a self-signed certificate, we now assume that the gateway is NOT using a self-signed certificate, when the user brings their own `cert-manager`.
This primarily fixes an issue where Pods would fail to start because we would try and mount the `trust-manager` Bundle ConfigMaps as volumes on Pods, but the Bundle would not exist when the user disables the embedded `cert-manager`.
> fix: don't mount trust bundles with own cert-manager

- generator/default_values.yaml
- generator/templates/argocd/applications/deploykf-dependencies/kyverno.yaml
- generator/templates/manifests/deploykf-dependencies/kyverno/templates/ClusterPolicy-image-pull-secrets.yaml
- generator/templates/manifests/deploykf-dependencies/kyverno/values.yaml
- scripts/sync_argocd_apps.sh
This PR adds a Kyverno ClusterPolicy which automatically replicates and injects Pod imagePullSecrets across the cluster.
This policy is primarily needed when using __private container registries__ or for avoiding DockerHub __pull limits__.
As the new ClusterPolicy lives in the embedded Kyverno chart, we had to make some small changes to the `sync_argocd_apps.sh` script. Previously, we were always force-syncing ClusterPolicies (with `clone` or `generate` in the name), even if they were "missing" from the cluster, which caused a failure on the first sync, as this would result in the ClusterPolicy being applied before its CRD.
> feat: kyverno policy for image-pull-secrets

- generator/templates/manifests/deploykf-core/deploykf-auth/templates/ClusterPolicy--restart-on-secret-updates.yaml
- generator/templates/manifests/deploykf-opt/deploykf-minio/templates/ClusterPolicy--restart-on-secret-updates.yaml
- generator/templates/manifests/deploykf-opt/deploykf-mysql/templates/ClusterPolicy--restart-on-secret-updates.yaml
- generator/templates/manifests/kubeflow-tools/katib/resources/restart-on-mysql-secret-update-clusterpolicy.yaml
- generator/templates/manifests/kubeflow-tools/pipelines/resources/restart-on-mysql-secret-update-clusterpolicy.yaml
- generator/templates/manifests/kubeflow-tools/pipelines/resources/restart-on-pipeline-configmap-update-clusterpolicy.yaml
This PR is a minor refactor to ensure we only use `apiVersion` = `kyverno.io/v1` for Kyverno resources.
As far I as I can tell they are equivalent in Kyverno version `1.10.0`.
> refactor: always use `v1` kyverno resources

- generator/default_values.yaml
- generator/templates/manifests/deploykf-dependencies/kyverno/values.yaml
This PR adds values to change the number of pod replicas for the various Kyverno deployments.
The only change from the previous default is that we now have 3 replicas for the admission-controller (rather than 1), as it scales horizontally, and is hit very hard, because in some cases it can be validating/mutating all Kubernetes API requests.
> feat: add values for kyverno replicas

- generator/default_values.yaml
- generator/templates/manifests/deploykf-dependencies/kyverno/values.yaml
This PR ensures that even if the user sets their own `deploykf_dependencies.kyverno.extraResourceRules`, that Kyverno will have the required RBAC permissions to manage `PodDefault` resources.
> fix: ensure kyverno has permission to manage PodDefaults

- generator/templates/manifests/kubeflow-tools/pipelines/resources/generate-profile-resources-clusterpolicy.yaml
Before this PR, if the `ConfigMap/profile-tools--kubeflow-pipelines` was not present in a Profile Namespace, for any reason, Kyvenro would spam its logs saying that it was missing.
> fix: prevent kyverno log spam on missing generate context

- generator/default_values.yaml
- generator/templates/manifests/deploykf-core/deploykf-profiles-generator/templates/profile.yaml
- sample-values.yaml
The PR allows you to disable the default `plugins` or `resourceQuotaSpec` for a specific profile by setting them to `[]` and `{}` respectively in that profile definition. Previously, these were interpreted as "false" so would have been assigned the defaults, even if explicitly set as empty.
For example, the following will now behave as expected:
```yaml
deploykf_core:
deploykf_profiles_generator:
profileDefaults:
plugins:
- kind: AwsIamForServiceAccount
spec:
awsIamRole: arn:aws:iam::000000000000:role/MY_ROLE_NAME
AnnotateOnly: true
resourceQuotaSpec:
hard:
pods: 100
profiles:
- name: profile-with-defaults
members: ...
- name: profile-with-no-plugins
plugins: []
members: ...
- name: profile-with-no-limits
resourceQuotaSpec: {}
members: ...
```
> feat: disable default plugins and resource-quotas in specific profiles

- generator/templates/manifests/kubeflow-tools/pipelines/files/viewer-pod-template.json
- generator/templates/manifests/kubeflow-tools/pipelines/patches/patch-ml-pipeline-deployment.yaml
- generator/templates/manifests/kubeflow-tools/pipelines/patches/patch-ml-pipeline-ui-deployment.yaml
- generator/templates/manifests/kubeflow-tools/pipelines/resources/generate-profile-resources-clusterpolicy.yaml
resolves: https://github.com/deployKF/deployKF/issues/75
IRSA bucket authentication did not work properly in Kubeflow Pipelines because there were [default values](https://github.com/kubeflow/pipelines/blob/2.0.0-alpha.7/backend/src/apiserver/config/config.json#L9-L13) for access-key environment variables like `OBJECTSTORECONFIG_ACCESSKEY`, `MINIO_ACCESS_KEY`, and `AWS_ACCESS_KEY_ID` which were preventing the AWS credential provider from using the Pod's IRSA authentication.
This PR simply explicitly sets all the access key env-vars to `""` when `kubeflow_tools.pipelines.objectStore.auth.fromEnv` is `false`, so they are ignored and IRSA auth is attempted.
PS: thanks to @flaccid for testing this fix.
> fix: using AWS IRSA with Kubeflow Pipelines

- generator/templates/manifests/deploykf-core/deploykf-istio-gateway/templates/gateway/EnvoyFilter-kubeflow-pipelines.yaml
- generator/templates/manifests/deploykf-core/deploykf-istio-gateway/templates/gateway/VirtualService-https-redirect.yaml
Currently, we use a `302` redirect for HTTP -> HTTPS which is breaking non-`GET` requests. This PR replaces the `302` with a `307` temporary redirect which should allow `POST` and other operations to succeed. 
References:
- https://developer.mozilla.org/en-US/docs/Web/HTTP/Redirections#temporary_redirections
> fix: use 307 status for HTTP redirects

- generator/default_values.yaml
- generator/helpers/deploykf-gateway.tpl
- generator/templates/manifests/deploykf-core/deploykf-istio-gateway/templates/gateway/ServiceEntry-gateway.yaml
- generator/templates/manifests/deploykf-core/deploykf-istio-gateway/templates/gateway/VirtualService-https-redirect.yaml
- generator/templates/manifests/deploykf-core/deploykf-istio-gateway/values.yaml
- sample-values.yaml
Previously we assumed the internal (on the istio gateway) and external (on the user-facing service/ingress) ports were always the same.
This PR introduces `deploykf_core.deploykf_istio_gateway.gatewayService.ports.http` and `deploykf_core.deploykf_istio_gateway.gatewayService.ports.https` which can be used to either:
1. Change the ports which the service for the embedded istio gateway listens on:
- _(to potentially make them different from the internal gateway ports, which might help users who want to use the same istio gateway deployment for more than just deployKF)_
2. Inform deployKF about which ports are actually seen by end-users:
- _(for users who are bringing their own gateway service, so that deployKF will correctly generate user-facing links with the correct port)_
By default, …
> feat: allow custom external service ports

- generator/default_values.yaml
- generator/templates/manifests/deploykf-core/deploykf-istio-gateway/templates/gateway/DestinationRule-notebooks-redirect.yaml
- generator/templates/manifests/deploykf-core/deploykf-istio-gateway/templates/gateway/DestinationRule-tensorboards-redirect.yaml
- generator/templates/manifests/deploykf-core/deploykf-istio-gateway/templates/gateway/Gateway.yaml
- generator/templates/manifests/deploykf-core/deploykf-istio-gateway/templates/gateway/ServiceEntry-gateway.yaml
- generator/templates/manifests/deploykf-core/deploykf-istio-gateway/templates/gateway/VirtualService-notebooks-redirect.yaml
- generator/templates/manifests/deploykf-core/deploykf-istio-gateway/templates/gateway/VirtualService-tensorboards-redirect.yaml
- generator/templates/manifests/deploykf-core/deploykf-istio-gateway/values.yaml
- generator/templates/manifests/kubeflow-tools/katib/patches/patch-katib-ui-virtualservice.yaml
- generator/templates/manifests/kubeflow-tools/notebooks/jupyter-web-app/patches/patch-jupyter-web-app-virtualservice.yaml
- generator/templates/manifests/kubeflow-tools/pipelines/patches/patch-metadata-grpc-virtualservice.yaml
- generator/templates/manifests/kubeflow-tools/pipelines/patches/patch-ml-pipeline-ui-virtualservice.yaml
- generator/templates/manifests/kubeflow-tools/tensorboards/tensorboards-web-app/patches/patch-tensorboards-web-app-virtualservice.yaml
- generator/templates/manifests/kubeflow-tools/volumes/volumes-web-app/patches/patch-volumes-web-app-virtualservice.yaml
This PR allows users to disable SNI matching on the gateway by adding a new value `deploykf_core.deploykf_istio_gateway.gateway.tls.matchSNI` (which defaults to `true`).
Users may need to disable SNI matching when they are putting the deployKF gateway behind their own proxy which is doing TLS Termination, as most cloud proxies will not forward the original requests SNI to the backend system (e.g. AWS ALB). This is a very common issue, which even has its own [Istio documentation page](https://istio.io/v1.19/docs/ops/common-problems/network-issues/#configuring-sni-routing-when-not-sending-sni).
As part of this PR, we needed to work around the fact that _Kubeflow Notebooks_ and _Kubeflow TensorBoards_ currently always set their VirtualServices `spec.hosts` to `*`. This is a problem because …
> feat: allow disabling SNI matching on gateway

- generator/default_values.yaml
- generator/helpers/check-values--incompatible-configs.tpl
- generator/templates/manifests/deploykf-core/deploykf-auth/templates/dex/Secret-config.yaml
- generator/templates/manifests/deploykf-core/deploykf-auth/templates/oauth2-proxy/Secret-config.yaml
- generator/templates/manifests/deploykf-core/deploykf-auth/values.yaml
- generator/templates/manifests/deploykf-core/deploykf-dashboard/values.yaml
- generator/templates/manifests/deploykf-core/deploykf-istio-gateway/templates/gateway/DestinationRule-https-redirect.yaml
- generator/templates/manifests/deploykf-core/deploykf-istio-gateway/templates/gateway/EnvoyFilter-ext-authz.yaml
- generator/templates/manifests/deploykf-core/deploykf-istio-gateway/templates/gateway/EnvoyFilter-kubeflow-pipelines.yaml
- generator/templates/manifests/deploykf-core/deploykf-istio-gateway/templates/gateway/Gateway-https-redirect.yaml
- generator/templates/manifests/deploykf-core/deploykf-istio-gateway/templates/gateway/Gateway.yaml
- generator/templates/manifests/deploykf-core/deploykf-istio-gateway/templates/gateway/VirtualService-https-redirect.yaml
- generator/templates/manifests/deploykf-core/deploykf-istio-gateway/values.yaml
- generator/templates/manifests/deploykf-opt/deploykf-minio/templates/minio/Deployment.yaml
- generator/templates/manifests/deploykf-opt/deploykf-minio/values.yaml
- generator/templates/manifests/kubeflow-dependencies/kubeflow-argo-workflows/templates/ConfigMap-argo-config.yaml
- generator/templates/manifests/kubeflow-dependencies/kubeflow-argo-workflows/values.yaml
This PR makes it possible to disable the HTTP->HTTPS redirect on the gateway with a new `deploykf_core.deploykf_istio_gateway.gateway.tls.redirect` value (default: `true`), and thus allows clients to talk over HTTP to the gateway.
We also introduced the `deploykf_core.deploykf_istio_gateway.gateway.tls.clientsUseHttps` value (default: `true`) which is how deployKF decides what protocol of links and cookies presented to client browsers.
__WARNING:__ There is only ONE case where clients should talk to the gateway over HTTP. When the "client" is a proxy/load-balancer that is providing the actual "end users" its own TLS termination, but is unable to communicate with the backend over HTTPS.
---
__Advanced Stuff:__
We implement authentication using EnvoyFilters, we insert a bunch of HTTP_FILTER …
> feat: allow disabling HTTPS redirect

- generator/templates/manifests/deploykf-core/deploykf-istio-gateway/templates/gateway/EnvoyFilter-ext-authz.yaml
As part of https://github.com/deployKF/deployKF/pull/66, we accidentally made it so that our authentication system would accept the special `kubeflow-pipelines-sdk` OIDC audience, even if `deploykf_core.deploykf_auth.dex.clients.kubeflowPipelinesSDK.enabled` was false, or `kubeflow_tools.pipelines.enabled` was disabled.
> fix: disallow out-of-band KFP audience when disabled

- generator/templates/manifests/deploykf-core/deploykf-auth/templates/oauth2-proxy/Secret-config.yaml
This PR prepends `__Secure-` to our token cookie name when `deploykf_core.deploykf_istio_gateway.gateway.tls.clientsUseHttps` is true (indicating that users are connecting to deplopyKF over HTTPS), as browsers require HTTPS for the `Secure` attribute to be set, which itself is required to use the `__Secure-` prefix.
https://developer.mozilla.org/en-US/docs/Web/HTTP/Cookies#__host-
We also set `cookie_domains` to an empty list in our oauth2-proxy configs, as previously oauth2-proxy was spamming `[WARNING] ...` logs because it could not match the cookie domain to requests (when using non-standard ports). This change should have no effect, as deployKF currently always uses the same `deploykf_core.deploykf_istio_gateway.gateway.hostname` for all services so there is no reason to "force" a …
> improve: use `__Secure-` cookie prefix and remove domains config

- generator/default_values.yaml
- generator/templates/manifests/deploykf-dependencies/cert-manager/values.yaml
closes: https://github.com/deployKF/deployKF/issues/59
This PR adds the `deploykf_dependencies.cert_manager.controller.podLabels` value, which allows users to set labels on the cert-manager controller Pods. This new value is required to make use of [Azure AD Workload Identity](https://azure.github.io/azure-workload-identity/docs/) in cert-manager. 
For example, you can now use the following values:
```yaml
deploykf_dependencies:
cert_manager:
controller:
podLabels:
azure.workload.identity/use: "true"
serviceAccount:
annotations:
azure.workload.identity/client-id: "00000000-0000-0000-0000-000000000000"
#azure.workload.identity/tenant-id: "00000000-0000-0000-0000-000000000000"
```
> feat: add pod-labels value for cert-manager controller

- generator/templates/manifests/deploykf-core/deploykf-auth/templates/ClusterPolicy--restart-on-secret-updates.yaml
- generator/templates/manifests/deploykf-dependencies/kyverno/values.yaml
- generator/templates/manifests/deploykf-opt/deploykf-minio/templates/ClusterPolicy--restart-on-secret-updates.yaml
- generator/templates/manifests/deploykf-opt/deploykf-mysql/templates/ClusterPolicy--restart-on-secret-updates.yaml
- generator/templates/manifests/kubeflow-tools/katib/resources/restart-on-mysql-secret-update-clusterpolicy.yaml
- generator/templates/manifests/kubeflow-tools/pipelines/resources/restart-on-mysql-secret-update-clusterpolicy.yaml
- generator/templates/manifests/kubeflow-tools/pipelines/resources/restart-on-pipeline-configmap-update-clusterpolicy.yaml
This PR addresses an incompatible change introduced in newer versions of the Kyverno chart, mainly that `kyverno.cleanupController.rbac.clusterRole.extraResources[0].verbs` now needs to be set.
It also cleans up two case where we set `mutateExistingOnPolicyUpdate: false` despite that being the default, and replaced instances of `{{ request.namespace }}` with `{{ request.object.metadata.namespace }}` because these seem to be problematic in Kyverno 1.11.
However, the Kyverno version remains as `1.10.0`, and we have left the chart version as `3.0.1`
---
__WARNING:__ We still can NOT update to any version of Kyverno from `1.10.1` to `1.11.4`, as all have problems that make them incompatible with deployKF:
- https://github.com/kyverno/kyverno/issues/9134
- …
> fix: support kyverno chart changes (but keep kyverno version)

- generator/default_values.yaml
- generator/templates/manifests/deploykf-dependencies/kyverno/values.yaml
This PR increases the default memory limit for the Kyverno background controller to `512Mi` and adds values to allow users to customize it further.
This was necessary because our version of Kyverno (1.10.0, which we must use due to issues in newer versions, see https://github.com/deployKF/deployKF/pull/92), uses more memory when running deployKF than is allowed by its default configs.
The following values have been added:
- `deploykf_dependencies.kyverno.admissionController.resources`
- `deploykf_dependencies.kyverno.backgroundController.resources`
- `deploykf_dependencies.kyverno.cleanupController.resources`
- `deploykf_dependencies.kyverno.reportsController.resources`
> improve: increase kyverno resource limits and add values

- generator/templates/argocd/applications/deploykf-dependencies/kyverno.yaml
- generator/templates/manifests/deploykf-dependencies/kyverno/values.yaml
This PR makes it so that we no longer have to enable ArgoCD's ServerSideApply feature at the application level for Kyverno.
We can instead work around the same issue ([where annotation limits are exceeded because Kyverno's CRDs are so big](https://kyverno.io/docs/installation/platform-notes/#notes-for-argocd-users)), by simply annotating the CRD resources with `argocd.argoproj.io/sync-options: "Replace=true"`.
> improve: use CRD-level "replace" for kyverno ArgoCD app

- generator/templates/manifests/deploykf-dependencies/kyverno/templates/ClusterPolicy-image-pull-secrets.yaml
This PR makes it so that secrets cloned by the `deploykf_dependencies.kyverno.clusterPolicies.imagePullSecrets` policy are annotated with `argocd.argoproj.io/compare-options: IgnoreExtraneous` and `argocd.argoproj.io/sync-options: Prune=false` to prevent ArgoCD pruning them or showing source secret's app as our of sync (if it comes from one).
> fix: annotate cloned imagePullSecrets to be ignored by ArgoCD

- generator/templates/manifests/deploykf-core/deploykf-auth/templates/ClusterPolicy--restart-on-secret-updates.yaml
- generator/templates/manifests/deploykf-core/deploykf-auth/templates/dex/ClusterPolicy-clone-argo-server-openid-secret.yaml
- generator/templates/manifests/deploykf-core/deploykf-auth/templates/dex/ClusterPolicy-clone-minio-openid-secret.yaml
- generator/templates/manifests/deploykf-core/deploykf-profiles-generator/templates/profile-tools--kubeflow-pipelines.yaml
- generator/templates/manifests/deploykf-opt/deploykf-minio/templates/ClusterPolicy--restart-on-secret-updates.yaml
- generator/templates/manifests/deploykf-opt/deploykf-mysql/templates/ClusterPolicy--restart-on-secret-updates.yaml
- generator/templates/manifests/kubeflow-dependencies/kubeflow-argo-workflows/templates/ClusterPolicy-clone-bucket-secret.yaml
- generator/templates/manifests/kubeflow-tools/katib/resources/clone-mysql-secret-clusterpolicy.yaml
- generator/templates/manifests/kubeflow-tools/katib/resources/restart-on-mysql-secret-update-clusterpolicy.yaml
- generator/templates/manifests/kubeflow-tools/pipelines/resources/clone-bucket-secret-clusterpolicy.yaml
- generator/templates/manifests/kubeflow-tools/pipelines/resources/clone-mysql-secret-clusterpolicy.yaml
- generator/templates/manifests/kubeflow-tools/pipelines/resources/restart-on-mysql-secret-update-clusterpolicy.yaml
- generator/templates/manifests/kubeflow-tools/pipelines/resources/restart-on-pipeline-configmap-update-clusterpolicy.yaml
This PR adds a precondition to filter out BACKGROUND events on our restart trigger policies.
This is needed because, in later versions of Kyverno, [each `BACKGROUND_SCAN_INTERVAL` the mutation will be applied](https://kyverno.io/docs/writing-policies/mutate/#mutate-existing-resources), which will cause our deployments to restart erroneously. 
Note, that this behavior ONLY applies to "mutate existing" rules (which define `targets`), so we don't need to update the other rules, like those that annotate the cloned secrets.
> fix: add background filter to restart trigger policies

- generator/templates/manifests/deploykf-core/deploykf-auth/templates/oauth2-proxy/Secret-config.yaml
- generator/templates/manifests/deploykf-core/deploykf-istio-gateway/templates/gateway/EnvoyFilter-ext-authz.yaml
closes https://github.com/deployKF/deployKF/issues/96
This PR tries to ensure that background queries do not get redirected to dex authentication (which will cause a CSRF cookie to be added to the browser), as around the cookie expiry time, we are seeing 431 errors (too large headers) due to too many CSRF cookies.
This PR makes two changes:
1. Ensures that `Accept` headers are actually passed to oauth2-proxy during ExtAuthZ:
- This is because oauth2-proxy will not redirect `application/json` requests which are unauthenticated, and instead just responds with 401. (See [oauth2-proxy behavior](https://oauth2-proxy.github.io/oauth2-proxy/behaviour)). 
2. Defines [`--api-route` / `api_routes`](https://oauth2-proxy.github.io/oauth2-proxy/configuration/overview#command-line-options) patterns for …
> fix: prevent CSRF cookie accumulation on auth expiry

- scripts/sync_argocd_apps.sh
This PR fixes a regression caused by https://github.com/deployKF/deployKF/pull/108, where only the first app in each sync group was being synced. Our bash splitting was not correcting parsing the newline-separated output of `argocd app list ...`.
> fix: argocd sync script only seeing first app in each group

- argocd-plugin/argocd-install/kustomization.yaml
This PR updates the default version of ArgoCD (in the example docs) from `2.9.6` to `2.10.4`.
Hopefully, this will resolve the minio post-install job race condition for some users:
- https://github.com/orgs/deployKF/discussions/113
> docs: update default argocd to 2.10.4

- scripts/sync_argocd_apps.sh
The required `bash` version for the `sync_argocd_apps.sh` script is actually 4.4+ (see https://github.com/deployKF/deployKF/issues/125).
> fix: require bash 4.4+ for sync script

- generator/templates/manifests/deploykf-core/deploykf-auth/templates/oauth2-proxy/VirtualService.yaml
This PR adds a `robots.txt` to the root of the domain to discourage all scrapers from indexing deployKF platforms (which really should NOT be on the public internet). We achieve this by exposing the `robots.txt` that is [served by `oauth2-proxy`](https://oauth2-proxy.github.io/oauth2-proxy/features/endpoints/).
The contents of the `robots.txt` is as follows:
```
User-agent: *
Disallow: /
```
> improve: add robots.txt to deny all user-agents

- generator/default_values.yaml
- generator/templates/manifests/deploykf-core/deploykf-auth/templates/dex/Deployment.yaml
- generator/templates/manifests/deploykf-core/deploykf-auth/templates/oauth2-proxy/Secret-config.yaml
This PR updates dex to `2.39.1`.
The new version of Dex supports disabling env-var expansion in the config file by setting `DEX_EXPAND_ENV` to `false`, we have done this. This is useful because there was previously no way to escape literal `$` characters that may appear in the users `deploykf_core.deploykf_auth.dex.connectors` configs https://github.com/dexidp/dex/pull/1902.
We also tell `oauth2-proxy` to not explicitly "force" the provider to prompt the user for consent during each login, as Dex now respects this request as of https://github.com/dexidp/dex/pull/3086.
> feat: update dex to 2.39.1

- generator/default_values.yaml
This PR updates the default kubectl container version to `1.26.15`.
This is used in things like pre-install jobs which generate secrets.
> feat: update kubectl container to 1.26.15

- generator/default_values.yaml
This PR updates the default Istio version to `1.17.8`.
__WARNING:__ to fully update, users will need to use the new `update_istio_sidecars.sh` script added in https://github.com/deployKF/deployKF/pull/132
__NOTE 1:__ this version is still quite out of date, but as we don't want to break support for old versions of Kubernetes in a patch release, we will do a more significant jump in the next minor release.
__NOTE 2:__ you can update these values to any [supported version of Istio](https://www.deploykf.org/releases/version-matrix/#istio), if you want to use a newer version.
> feat: update default istio to 1.17.8

- generator/default_values.yaml
- generator/templates/manifests/deploykf-opt/deploykf-minio/templates/minio/Job-create-buckets.yaml
- generator/templates/manifests/deploykf-opt/deploykf-minio/templates/minio/Job-create-policies.yaml
- generator/templates/manifests/deploykf-opt/deploykf-minio/templates/minio/Job-create-service-accounts.yaml
- generator/templates/manifests/deploykf-opt/deploykf-minio/values.yaml
This PR updates the default MinIO version to `RELEASE.2024-05-10T01-41-38Z`.
__NOTE:__ because the `minio/mc` docker image has had all non `mc` binaries removed (specifically, `curl` and `jq`), we now use a combination of the following images for our pre-install jobs (which do things like generating S3-like access key secrets for KFP):
- `docker.io/bitnami/minio-client:2024.5.9-debian-12-r0` (for the `mc` binary)
- `docker.io/bitnami/os-shell:12-debian-12-r20` (for the `curl` and `jq` binaries, and to actually run the jobs)
> feat: update default minio to `RELEASE.2024-05-10T01-41-38Z`

- generator/default_values.yaml
- generator/templates/manifests/deploykf-core/deploykf-dashboard/templates/kfam-api/Deployment.yaml
- generator/templates/manifests/deploykf-core/deploykf-dashboard/templates/profile-controller/Deployment.yaml
- generator/templates/manifests/deploykf-core/deploykf-dashboard/values.yaml
- generator/templates/manifests/deploykf-core/deploykf-profiles-generator/templates/profile.yaml
This PR updates the `profile-controller` and `kfam-api` to their 1.8.0 versions.
This allows us to remove the `ns-owner-access-istio--override` AuthorizationPolicy in each Profile Namespace, as the upstream profile controller will now correctly create the `ns-owner-access-istio` AuthorizationPolicy with source principals.
Additionally, this change means these core components now have native ARM64 Docker images.
I also realised we were needlessly setting the UID/GID of the Pods to `0`, when we can use [the non-root `65532`](https://github.com/GoogleContainerTools/distroless/blob/761e3d2e151f080ed5c80cd1f26c12d68bd89ad9/common/variables.bzl#L18) for distroless images.
> feat: update profile-controller and kfam to 1.8.0

- generator/default_values.yaml
- generator/templates/manifests/deploykf-core/deploykf-dashboard/templates/central-dashboard/VirtualService.yaml
- generator/templates/manifests/deploykf-core/deploykf-dashboard/templates/kfam-api/AuthorizationPolicy-deny.yaml
- generator/templates/manifests/deploykf-core/deploykf-dashboard/values.yaml
This PR updates the deployKF Dashboard to [0.1.1](https://github.com/deployKF/dashboard/releases/tag/v0.1.1), this comes with numerous security and feature updates.
This PR also does the following:
- updates the sidebar links of the dashboard so that the Kubeflow Pipelines links are in their own section, which reduces clutter as there are so many.
- updates the Argo Server link to ensure users don't get confused by trying to list workflows at the cluster level (which happens if no namespace selector is applied), which causes RBAC errors as no normal user can do this.
- explicitly denies profiles owners the ability to manage profile contributors in the UI, as this should be done with deployKF values in GitOps
> feat: update dashboard to 0.1.1 + update sidebar links

- generator/default_values.yaml
This PR updates the default Kubeflow Notebooks images to use the upstream `1.8.0` tags.
This is a significant update that we worked on upstream in https://github.com/kubeflow/kubeflow/pull/7357 and https://github.com/kubeflow/kubeflow/pull/7398 which comes with ARM64 support for all non-CUDA images and many other updates.
In the near future, we will create official deployKF notebook images with versions aligned to deployKF and other useful changes that you will be able to base your custom images on. However, we still recommend updating your images to these 1.8.0 versions in the meantime.
__NOTE:__ you will need to manually delete and recreate all your Notebook servers for this change to take effect, this update ___only affects the SPAWNER UI___, not existing notebooks.
> feat: update default notebook images to 1.8.0

- generator/default_values.yaml
- generator/templates/manifests/deploykf-opt/deploykf-minio/templates/minio/Deployment.yaml
This PR fixes an error introduced by https://github.com/deployKF/deployKF/pull/158 (which was never part of a release).
The issue is that `curl` has been removed from the upstream MinIO images (`docker.io/minio/minio)`. Therefore, in this PR we have moved to the Bitnami ones (`docker.io/bitnami/minio`), as they have no pull limit on Dockerhub and still contain the `curl` binary.
For reference, we need the curl binary to check that dex is up before starting MinIO. If dex is not up before MinIO starts, then it will never try to access the OpenID provider again, and there will be no way to log in.
> fix: minio not starting, upstream removed curl
