deployKF/deployKF

- .github/workflows/release.yml
- .gitignore
> ci: add release workflow

- README.md
> docs: update readme and version info

- README.md
> docs: improve getting started formatting

- README.md
> docs: improve getting started guide

- README.md
> docs: add link to youtube demo

- README.md
After a significant update to the deployKF website, the "getting started" guide in the readme is no longer needed.
> docs: move guides to website

- gen_with_gomplate.sh
Fixes an issue in the `gen_with_gomplate.sh` development script.
> chore: fix `gen_with_gomplate.sh`

- argocd-plugin/README.md
- argocd-plugin/example-app-of-apps/app-of-apps.yaml
- argocd-plugin/example-app-of-apps/apply_apps_of_apps.sh
This PR improves the example `app-of-apps` for the deployKF ArgoCD Plugin, to better demonstrate how to set and override values.
> docs: improve example app-of-apps for plugin

- sample-values-overrides.yaml
- sample-values.yaml
This PR improves the existing `sample-values.yaml`, and adds a new `sample-values-overrides.yaml` as a reference of how someone might apply overrides directly on top of `sample-values.yaml`, without modifying it directly.
The new `sample-values-overrides.yaml` also includes links to relevant guides on the website, and commented out examples of what the user might want to set.
> docs: improve sample values, add reference overrides

- scripts/sync_argocd_apps.sh
This PR updates the `sync_argocd_apps.sh` script so that it will automatically use `kubectl replace --force` with Kyverno ClusterPolicies that have a "generate" type rule.
This is needed because Kyverno does not have a method for updating these policies/rules without deleting and recreating the whole ClusterPolicy: https://github.com/kyverno/kyverno/issues/7718
We can remove this additional complexity once Argo CD adds the `argocd.argoproj.io/sync-options: Force=true` annotation, which allows us to use force syncing with only specific resources: https://github.com/argoproj/gitops-engine/issues/414
> docs: update sync script to force update kyverno policies

- generator/templates/manifests/deploykf-core/deploykf-auth/templates/dex/ClusterPolicy-clone-argo-server-openid-secret.yaml
- generator/templates/manifests/deploykf-core/deploykf-auth/templates/dex/ClusterPolicy-clone-minio-openid-secret.yaml
- generator/templates/manifests/deploykf-core/deploykf-profiles-generator/templates/profile-tools--kubeflow-pipelines.yaml
- generator/templates/manifests/kubeflow-dependencies/kubeflow-argo-workflows/templates/ClusterPolicy-clone-bucket-secret.yaml
- generator/templates/manifests/kubeflow-tools/katib/resources/clone-mysql-secret-clusterpolicy.yaml
- generator/templates/manifests/kubeflow-tools/pipelines/resources/clone-bucket-secret-clusterpolicy.yaml
- generator/templates/manifests/kubeflow-tools/pipelines/resources/clone-mysql-secret-clusterpolicy.yaml
This PR makes a small improvement to the Kyverno policies which ensures they only run on `CREATE` and `UPDATE` operations.
> improve: limit trigger operations for kyverno policies

- argocd-plugin/argocd-install/deploykf-plugin/repo-server-patch.yaml
- argocd-plugin/argocd-install/kustomization.yaml
This PR updates the reference ArgoCD version used by the `install_argocd.sh` script to `2.8.5`.
> docs: update reference argocd version to 2.8.5

- argocd-plugin/argocd-install/kustomization.yaml
This PR simply changes the example version of Argo CD from 2.8.5 to 2.9.6.
> docs: update example ArgoCD to 2.9.6

- scripts/sync_argocd_apps.sh
This PR improves the `sync_argocd_apps.sh` script in the following ways:
- Only wait for each app to become healthy one time. Previously, we waited once after the sync (for the out-of-sync apps we just synced), and again for all the apps (even the ones which were not synced). Now we only do the second one.
- Increases the default `ARGOCD_PRUNE_PROMPT_SECONDS` to 60 seconds
- Improves the warning about pruning to explain that ArgoCD incorrectly displays resources that have `argocd.argoproj.io/sync-options: Prune=false` annotation as requiring pruning, when during an actual prune sync, they are not actually pruned:
- https://github.com/argoproj/argo-cd/issues/17188
- Improves the force-sync feature to also work with namespaced resources:
- _(NOTE: we currently still only use it for …
> improve: argocd sync script should only wait for app health once

- scripts/sync_argocd_apps.sh
This PR updates the `sync_argocd_apps.sh` script to support the `argocd.appNamePrefix` value being set. We achieve this by introducing a new script config called `ARGOCD_APP_NAME_PREFIX` which must be set to the same value as the `argocd.appNamePrefix` of the deployKF instance which you want to sync.
Before this change, running the script would result in syncing all deployKF clusters managed by the ArgoCD instance, which is probably not what the user wants.
This change also makes it so that if we don't detect the `deploykf-app-of-apps` Application, the sync will immediately fail.
> improve: support `argocd.appNamePrefix` in argocd sync script

- argocd-plugin/README.md
- argocd-plugin/argocd-helm/helm_install_argocd.sh
- argocd-plugin/argocd-helm/helm_upgrade_argocd.sh
- argocd-plugin/argocd-helm/values.yaml
- argocd-plugin/argocd-install/deploykf-plugin/assets-pvc.yaml
- argocd-plugin/argocd-install/deploykf-plugin/plugin.yaml
- argocd-plugin/example-app-of-apps/app-of-apps.yaml
This PR updates the `argocd-plugin` docs to explain how to use the plugin with an existing Helm-based ArgoCD install.
> docs: add argocd helm example for plugin

- scripts/sync_argocd_apps.sh
Previously, the `sync_argocd_apps.sh` script allowed users to skip pruning while syncing (and this was actually the default behavior if a user did not respond to the prompt for 60 seconds). This was causing many users to accidentally not prune resources, which can break things like authentication (Istio resources), and more.
Specifically, the following changes have been made:
- All configs can now be set from exported environment variables (rather than only by updating the script itself)
- The logs are now more clear.
- We have added a new `ARGOCD_PRUNE_MODE` called `ask`, which is the new default:
-  this mode will ask the user (each time they run the script) to decide if they want to `ALWAYS prune` or `PROMPT for each` (which correspond to the other values of `ARGOCD_PRUNE_MODE`)
- The …
> fix: require pruning in sync script

- .github/ISSUE_TEMPLATE/01_bug_report.yml
- .github/ISSUE_TEMPLATE/02_feature_request.yml
We need a little more information from users, so we are updating the GitHub issue templates.
> chore: update github issue templates

- scripts/sync_argocd_apps.sh
This PR updates the `sync_argocd_apps.sh` so that it will also sync apps whose last sync failed, in addition to those that are actually "out of sync".
This only affects apps where a `pre-install` Job succeeded one time, but failed the next, in these cases, the overall app might have looked "in sync" from ArgoCD's perspective, but in actuality, since the `pre-install` job failed, it needs to be re-synced before continuing with future syncs.
> fix: script should sync apps that failed their last sync

- generator/default_values.yaml
This PR updates `oauth2-proxy` to `7.6.0`, which should be safe to do in-place.
> feat: update oauth2-proxy to 7.6.0

- generator/default_values.yaml
This PR updates cert-manager to `1.12.10`, the latest LTS version.
> feat: update cert-manager to 1.12.10

- generator/default_values.yaml
This PR updates the default MySQL version to `8.0.37`.
> feat: update default mysql to 8.0.37

- generator/default_values.yaml
- sample-values-overrides.yaml
- sample-values.yaml
This PR removes confusing defaults from the `sample-values.yaml`, and updates the links in `sample-values-overrides.yaml` to reflect the current state of the deployKF website.
> docs: remove confusing sample values

- generator/default_values.yaml
- generator/templates/manifests/deploykf-dependencies/cert-manager/forks/trust-manager/Chart.yaml
- generator/templates/manifests/deploykf-dependencies/cert-manager/forks/trust-manager/templates/NOTES.txt
- generator/templates/manifests/deploykf-dependencies/cert-manager/forks/trust-manager/templates/_helpers.tpl
- generator/templates/manifests/deploykf-dependencies/cert-manager/forks/trust-manager/templates/certificate.yaml
- generator/templates/manifests/deploykf-dependencies/cert-manager/forks/trust-manager/templates/clusterrole.yaml
- generator/templates/manifests/deploykf-dependencies/cert-manager/forks/trust-manager/templates/clusterrolebinding.yaml
- generator/templates/manifests/deploykf-dependencies/cert-manager/forks/trust-manager/templates/deployment.yaml
- generator/templates/manifests/deploykf-dependencies/cert-manager/forks/trust-manager/templates/metrics-service.yaml
- generator/templates/manifests/deploykf-dependencies/cert-manager/forks/trust-manager/templates/metrics-servicemonitor.yaml
- generator/templates/manifests/deploykf-dependencies/cert-manager/forks/trust-manager/templates/poddisruptionbudget.yaml
- generator/templates/manifests/deploykf-dependencies/cert-manager/forks/trust-manager/templates/role.yaml
- generator/templates/manifests/deploykf-dependencies/cert-manager/forks/trust-manager/templates/rolebinding.yaml
- generator/templates/manifests/deploykf-dependencies/cert-manager/forks/trust-manager/templates/serviceaccount.yaml
- generator/templates/manifests/deploykf-dependencies/cert-manager/forks/trust-manager/templates/trust.cert-manager.io_bundles.yaml
- generator/templates/manifests/deploykf-dependencies/cert-manager/forks/trust-manager/templates/webhook.yaml
- generator/templates/manifests/deploykf-dependencies/cert-manager/forks/trust-manager/values.yaml
This PR updates trust-manager to `0.9.2`.
As part of this update, we have updated our embedded fork of the trust-manager helm chart, which is still required because they have not added the values we need upstream.
> feat: update trust-manager to 0.9.2

- argocd-plugin/argocd-helm/helm_install_argocd.sh
- argocd-plugin/argocd-helm/helm_upgrade_argocd.sh
- argocd-plugin/argocd-install/kustomization.yaml
This PR updates the default ArgoCD version in our docs to 2.10.11.
Other versions are still supported.
> docs: update default argocd to 2.10.11
